### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by bioinformaticss** [larsgr/BSplineMI#1]
Hey There, 

Thanks a lot for implementing the algorithm. I am interested to use it however, it turns out that I cannot install it here is the error I got: 

> Error
> 
>  in dyn.load(file, DLLpath = DLLpath, ...) :
>   unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/BSplineMI/libs/BSplineMI.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/BSplineMI/libs/BSplineMI.so, 6): Symbol not found: _omp_set_num_threads
>   Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/BSplineMI/libs/BSplineMI.so
>   Expected in: flat namespace
>  in /Library/Frameworks/R.framework/Versions/3.3/Resources/library/BSplineMI/libs/BSplineMI.so
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/BSplineMI’`

**Comment by larsgr** [comment]
Hi

It seems like your compiler doesn't support openMP, which was used for multi-threading. Added #ifdef _OPENMP around the openMP code so that it now should compile without parallel support.

Could you please try again and tell me if it works now?

**Comment by rimorob** [comment]
I have a similar problem, except my compiler bails out due to -fopenmp flag.  Can I somehow turn it off from the R command line?  Don't need parallel processing right now.

**Comment by larsgr** [comment]
I have added a check for openMP in the autoconf script. Now it should be able to compile without openMP.
